harness = "v9"
plugins = [
    "adplug",
    "art_of_noise",
    "asap",
    "audio_stream",
    "cpsycle",
    "eupmini",
    "fmplayer",
    "furnace",
    "gme",
    "hively",
    "ixalance",
    "klystrack",
    "libkss",
    "libvgm",
    "mdxmini",
    "openmpt",
    "organya",
    "pmdmini",
    "pretracker",
    "pxtone",
    "sc68",
    "sidplayfp",
    "spu",
    "sunvox",
    "tfmx",
    "uade",
    "v2m",
    "xsf",
    "zxtune",
]
