/* Config.h - Generated by CMake for libtfmxaudiodecoder */

#ifndef CONFIG_H
#define CONFIG_H

/* Define to 1 if you have the <dlfcn.h> header file. */
#define HAVE_DLFCN_H 1

/* Define to 1 if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES_H 1

/* Define to 1 if you have the <stdint.h> header file. */
#define HAVE_STDINT_H 1

/* Define to 1 if you have the <stdio.h> header file. */
#define HAVE_STDIO_H 1

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define to 1 if you have the <strings.h> header file. */
#define HAVE_STRINGS_H 1

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* Define to 1 if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H 1

/* Define to 1 if the system has the type '_Bool'. */
#define HAVE__BOOL 1

/* Define to 1 if all of the C89 standard headers exist */
#define STDC_HEADERS 1

/* Package info */
#define PACKAGE "libtfmxaudiodecoder"
#define PACKAGE_NAME "libtfmxaudiodecoder"
#define PACKAGE_VERSION "1.0.1"
#define PACKAGE_STRING "libtfmxaudiodecoder 1.0.1"
#define VERSION "1.0.1"

#endif /* CONFIG_H */
